// eslint-disable-next-line import/prefer-default-export
import { FunctionKeyWord } from '../token-categories.js';
import * as Types from '../../types.d.js';

/** @type {Types.KeywordObject[]} */

// eslint-disable-next-line import/prefer-default-export
export const logicalFunctionList = [
    {
        name: 'IIF',
        categories: [FunctionKeyWord],
        function: 'IF',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'iif',
        categories: [FunctionKeyWord],
        function: 'IF',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'AND',
        categories: [FunctionKeyWord],
        function: 'AND',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'and',
        categories: [FunctionKeyWord],
        function: 'AND',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'OR',
        categories: [FunctionKeyWord],
        function: 'OR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'or',
        categories: [FunctionKeyWord],
        function: 'OR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'XOR',
        categories: [FunctionKeyWord],
        function: 'OR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'xor',
        categories: [FunctionKeyWord],
        function: 'OR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'NOT',
        categories: [FunctionKeyWord],
        function: 'NOT',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'not',
        categories: [FunctionKeyWord],
        function: 'NOT',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISNULL',
        categories: [FunctionKeyWord],
        function: 'ISNULL',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isNull',
        categories: [FunctionKeyWord],
        function: 'ISNULL',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISUNDEFINED',
        categories: [FunctionKeyWord],
        function: 'ISUNDEFINED',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isUndefined',
        categories: [FunctionKeyWord],
        function: 'ISUNDEFINED',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISERROR',
        categories: [FunctionKeyWord],
        function: 'ISERROR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isError',
        categories: [FunctionKeyWord],
        function: 'ISERROR',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISBLANK',
        categories: [FunctionKeyWord],
        function: 'ISBLANK',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isBlank',
        categories: [FunctionKeyWord],
        function: 'ISBLANK',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISNUMBER',
        categories: [FunctionKeyWord],
        function: 'ISNUMBER',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isNumber',
        categories: [FunctionKeyWord],
        function: 'ISNUMBER',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISLOGICAL',
        categories: [FunctionKeyWord],
        function: 'ISLOGICAL',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isLogical',
        categories: [FunctionKeyWord],
        function: 'ISLOGICAL',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'ISDATE',
        categories: [FunctionKeyWord],
        function: 'ISDATE',
        type: 'Function',
        returns: 'Boolean',
    },
    {
        name: 'isDate',
        categories: [FunctionKeyWord],
        function: 'ISDATE',
        type: 'Function',
        returns: 'Boolean',
    },
];
