// eslint-disable-next-line import/prefer-default-export
import { FunctionKeyWord } from '../token-categories.js';
import * as Types from '../../types.d.js';

/** @type {Types.KeywordObject[]} */

// eslint-disable-next-line import/prefer-default-export
export const numericFunctionList = [
    {
        name: 'MOD',
        categories: [FunctionKeyWord],
        function: 'MOD',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'mod',
        categories: [FunctionKeyWord],
        function: 'MOD',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'POWER',
        categories: [FunctionKeyWord],
        function: 'POWER',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'power',
        categories: [FunctionKeyWord],
        function: 'POWER',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'EXP',
        categories: [FunctionKeyWord],
        function: 'EXP',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'exp',
        categories: [FunctionKeyWord],
        function: 'EXP',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ROUND',
        categories: [FunctionKeyWord],
        function: 'ROUND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'round',
        categories: [FunctionKeyWord],
        function: 'ROUND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'CEILING',
        categories: [FunctionKeyWord],
        function: 'CEILING',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ceiling',
        categories: [FunctionKeyWord],
        function: 'CEILING',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'FLOOR',
        categories: [FunctionKeyWord],
        function: 'FLOOR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'floor',
        categories: [FunctionKeyWord],
        function: 'FLOOR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ABS',
        categories: [FunctionKeyWord],
        function: 'ABS',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'abs',
        categories: [FunctionKeyWord],
        function: 'ABS',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SQRT',
        categories: [FunctionKeyWord],
        function: 'SQRT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'sqrt',
        categories: [FunctionKeyWord],
        function: 'SQRT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'PRODUCT',
        categories: [FunctionKeyWord],
        function: 'PRODUCT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'product',
        categories: [FunctionKeyWord],
        function: 'PRODUCT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'LEN',
        categories: [FunctionKeyWord],
        function: 'LEN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'len',
        categories: [FunctionKeyWord],
        function: 'LEN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MONTH',
        categories: [FunctionKeyWord],
        function: 'MONTH',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'month',
        categories: [FunctionKeyWord],
        function: 'MONTH',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'YEAR',
        categories: [FunctionKeyWord],
        function: 'YEAR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'year',
        categories: [FunctionKeyWord],
        function: 'YEAR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'HOUR',
        categories: [FunctionKeyWord],
        function: 'HOUR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'hour',
        categories: [FunctionKeyWord],
        function: 'HOUR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MINUTE',
        categories: [FunctionKeyWord],
        function: 'MINUTE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'minute',
        categories: [FunctionKeyWord],
        function: 'MINUTE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SECOND',
        categories: [FunctionKeyWord],
        function: 'SECOND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'second',
        categories: [FunctionKeyWord],
        function: 'SECOND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SUM',
        categories: [FunctionKeyWord],
        function: 'SUM',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'sum',
        categories: [FunctionKeyWord],
        function: 'SUM',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'AVERAGE',
        categories: [FunctionKeyWord],
        function: 'AVERAGE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'average',
        categories: [FunctionKeyWord],
        function: 'AVERAGE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MAX',
        categories: [FunctionKeyWord],
        function: 'MAX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'max',
        categories: [FunctionKeyWord],
        function: 'MAX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MIN',
        categories: [FunctionKeyWord],
        function: 'MIN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'min',
        categories: [FunctionKeyWord],
        function: 'MIN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'CHARINDEX',
        categories: [FunctionKeyWord],
        function: 'CHARINDEX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'charIndex',
        categories: [FunctionKeyWord],
        function: 'CHARINDEX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'FIND',
        categories: [FunctionKeyWord],
        function: 'FIND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'find',
        categories: [FunctionKeyWord],
        function: 'FIND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SEARCH',
        categories: [FunctionKeyWord],
        function: 'FIND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'search',
        categories: [FunctionKeyWord],
        function: 'FIND',
        type: 'Function',
        returns: 'Numeric',
    },

];
