// eslint-disable-next-line import/prefer-default-export
import { NumericFunction } from '../token-categories.js';
import * as Types from '../../types.d.js';

/** @type {Types.KeywordObject[]} */

// eslint-disable-next-line import/prefer-default-export
export const numericFunctionList = [
    {
        name: 'MOD',
        categories: [NumericFunction],
        function: 'MOD',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'mod',
        categories: [NumericFunction],
        function: 'MOD',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'POWER',
        categories: [NumericFunction],
        function: 'POWER',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'power',
        categories: [NumericFunction],
        function: 'POWER',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'EXP',
        categories: [NumericFunction],
        function: 'EXP',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'exp',
        categories: [NumericFunction],
        function: 'EXP',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ROUND',
        categories: [NumericFunction],
        function: 'ROUND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'round',
        categories: [NumericFunction],
        function: 'ROUND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'CEILING',
        categories: [NumericFunction],
        function: 'CEILING',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ceiling',
        categories: [NumericFunction],
        function: 'CEILING',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'FLOOR',
        categories: [NumericFunction],
        function: 'FLOOR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'floor',
        categories: [NumericFunction],
        function: 'FLOOR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'ABS',
        categories: [NumericFunction],
        function: 'ABS',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'abs',
        categories: [NumericFunction],
        function: 'ABS',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SQRT',
        categories: [NumericFunction],
        function: 'SQRT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'sqrt',
        categories: [NumericFunction],
        function: 'SQRT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'PRODUCT',
        categories: [NumericFunction],
        function: 'PRODUCT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'product',
        categories: [NumericFunction],
        function: 'PRODUCT',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'LEN',
        categories: [NumericFunction],
        function: 'LEN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'len',
        categories: [NumericFunction],
        function: 'LEN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MONTH',
        categories: [NumericFunction],
        function: 'MONTH',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'month',
        categories: [NumericFunction],
        function: 'MONTH',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'YEAR',
        categories: [NumericFunction],
        function: 'YEAR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'year',
        categories: [NumericFunction],
        function: 'YEAR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'HOUR',
        categories: [NumericFunction],
        function: 'HOUR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'hour',
        categories: [NumericFunction],
        function: 'HOUR',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MINUTE',
        categories: [NumericFunction],
        function: 'MINUTE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'minute',
        categories: [NumericFunction],
        function: 'MINUTE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SECOND',
        categories: [NumericFunction],
        function: 'SECOND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'second',
        categories: [NumericFunction],
        function: 'SECOND',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SUM',
        categories: [NumericFunction],
        function: 'SUM',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'sum',
        categories: [NumericFunction],
        function: 'SUM',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'AVERAGE',
        categories: [NumericFunction],
        function: 'AVERAGE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'average',
        categories: [NumericFunction],
        function: 'AVERAGE',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MAX',
        categories: [NumericFunction],
        function: 'MAX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'max',
        categories: [NumericFunction],
        function: 'MAX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'MIN',
        categories: [NumericFunction],
        function: 'MIN',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'min',
        categories: [NumericFunction],
        function: 'MIN',
        type: 'Function',
        returns: 'Numeric',
    },

];
