import { StringFunction } from '../token-categories.js';
import * as Types from '../../types.d.js';

/** @type {Types.KeywordObject[]} */

// eslint-disable-next-line import/prefer-default-export
export const stringFunctionList = [
    {
        name: 'CONCATENATE',
        categories: [StringFunction],
        function: 'CONCATENATE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'concatenate',
        categories: [StringFunction],
        function: 'CONCATENATE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'LEFT',
        categories: [StringFunction],
        function: 'LEFT',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'left',
        categories: [StringFunction],
        function: 'LEFT',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'RIGHT',
        categories: [StringFunction],
        function: 'RIGHT',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'right',
        categories: [StringFunction],
        function: 'RIGHT',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'MID',
        categories: [StringFunction],
        function: 'MID',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'mid',
        categories: [StringFunction],
        function: 'MID',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'LOWER',
        categories: [StringFunction],
        function: 'LOWER',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'lower',
        categories: [StringFunction],
        function: 'LOWER',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'UPPER',
        categories: [StringFunction],
        function: 'UPPER',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'upper',
        categories: [StringFunction],
        function: 'UPPER',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'TRIM',
        categories: [StringFunction],
        function: 'TRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'trim',
        categories: [StringFunction],
        function: 'TRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'RTRIM',
        categories: [StringFunction],
        function: 'RTRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'rtrim',
        categories: [StringFunction],
        function: 'RTRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'LTRIM',
        categories: [StringFunction],
        function: 'LTRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'ltrim',
        categories: [StringFunction],
        function: 'LTRIM',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'REPLACE',
        categories: [StringFunction],
        function: 'REPLACE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'replace',
        categories: [StringFunction],
        function: 'REPLACE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'REPLICATE',
        categories: [StringFunction],
        function: 'REPLICATE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'replicate',
        categories: [StringFunction],
        function: 'REPLICATE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'CHARINDEX',
        categories: [],
        function: 'CHARINDEX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'charIndex',
        categories: [],
        function: 'CHARINDEX',
        type: 'Function',
        returns: 'Numeric',
    },
    {
        name: 'SUBSTRING',
        categories: [StringFunction],
        function: 'SUBSTRING',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'substring',
        categories: [StringFunction],
        function: 'SUBSTRING',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'REVERSE',
        categories: [StringFunction],
        function: 'REVERSE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'reverse',
        categories: [StringFunction],
        function: 'REVERSE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'SUBSTITUTE',
        categories: [StringFunction],
        function: 'SUBSTITUTE',
        type: 'Function',
        returns: 'String',
    },
    {
        name: 'substitute',
        categories: [StringFunction],
        function: 'SUBSTITUTE',
        type: 'Function',
        returns: 'String',
    },
];
